### PR TITLE
Add region flag

### PR DESCRIPTION
**Pull request by dkeza**
Added flag --region (-r) to set region on Heroku, when creating app. Default is us region.
#1

### CODE REVIEW

**Comment by markbates** [comment]
@dkeza I was just about to review this. Why did you close it?

**Comment by dkeza** [comment]
> @dkeza I was just about to review this. Why did you close it?

I just released, that I should create PR to developer branch.

**Comment by dkeza** [comment]
@markbates I have rebased my PR to master. But I think those check errors have nothing to do with my tiny change. I looked into log files, and saw this:
`go build github.com/gobuffalo/buffalo-plugins/plugins/plugdeps: module requires Go 1.12`

**Comment by markbates** [comment]
@dkeza it's actually because of this bug https://github.com/golang/go/issues/30446 I've updated the tests to use `1.11.5`. that should fix that issue, at least.

**Review by markbates — APPROVED** [review]

**Comment by markbates** [comment]
Thanks!

**Pull request merged**
